name: MSYS2 release
on:
  push:
    tags:
      - '*'

jobs:
  msys2-:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-isl mingw-w64-x86_64-gettext make texinfo
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload msys artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nios-gdb.tar.xz
          asset_name: nios-gdb.tar.xz
          asset_content_type: application/xz